#! /bin/sh

case "$1" in
	remove)
	    ;;
	purge)
		if [ -e /usr/share/debconf/confmodule ]; then
		    . /usr/share/debconf/confmodule
		    db_purge handballer 
		    echo "Purging debconf entries..."
		fi
		echo "Purging init entries..."
		update-rc.d -f handballer remove > /dev/null
		echo "Purging logfiles .."
		rm -rf /var/log/handballer
		;;
	upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
		;;
esac

