#!/bin/sh

set -e

case "$1" in
	configure)
		echo "Updating rc.d symbolic links to start handballer upon booting."
		update-rc.d handballer defaults 20 > /dev/null
		echo "Starting handballer ..."
		if [ -x /usr/sbin/invoke-rc.d ]; then
			invoke-rc.d handballer start  > /dev/null || true
		else
			/etc/init.d/handballer start  > /dev/null || true
		fi		
		;;
	*)
		#
		#	Unknown action - do nothing.
		#
		exit 0
		;;
esac

